site_title = "MyArxiv"
limit_days = 28
cache_url = "https://gaojingtong.github.io/MyArxiv/cache.json"

[[sources]]
limit = 450
category = "cs.IR"
title = "Information Retrieval"

[[sources]]
limit = 450
category = "cs.CL"
title = "Computation and Language"

[[sources]]
limit = 450
category = "cs.AI"
title = "Artificial Intelligence"

[[sources]]
limit = 450
category = "cs.LG"
title = "Machine Learning"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
